ID = 'com.emer.emergent'
Name = 'emergent'
Type = 'Library'
Version = 'v2.0.0-dev0.0.8'

[Generate]
  [Generate.Gtigen]
    AddTypes = true

[Release]
  Package = 'emer'
  VersionFile = 'emer/version.go'

